#!/usr/bin/python3
from battles import *
from improve_loadout import improve_loadout
from regain_health import regain_health
from text_display_tools import center_text, sleep_print


def after_beast_battle_story() -> None:
    """Displays the game's storyline after the hero defeats the beast.
    :return: None
    """
    from hero import hero  # Placing the import statement here to avoid a circular import error
    print()
    sleep_print()
    print(center_text("After the battle the other beasts start to disintegrate."))
    print()
    sleep_print()
    print(center_text("The wind picks up and blows away the remnants."))
    print()
    sleep_print()
    print(center_text("Eventually the land is free of the beasts."))
    print()
    sleep_print()
    print(center_text("The hero walks around looking around at the changes."))
    print()
    sleep_print()
    print(center_text("Green grass appears and spreads out."))
    print()
    sleep_print()
    print(center_text("All types of flowers bloom within the lush blades."))
    print()
    sleep_print()
    print(center_text("Trees shoot up from the ground and extend their branches."))
    regain_health()
    improve_loadout()
    print()
    print(center_text("An evil scream reverberates through the land."))
    print()
    sleep_print()
    print(center_text("The hero and the residents look around in confusion."))
    print()
    sleep_print()
    print(center_text("Then the malevolent voice returns:"))
    print()
    sleep_print()
    print(center_text("\"You defeated my beast?\""))
    print()
    sleep_print()
    print(center_text("\"I underestimated you.\""))
    print()
    sleep_print()
    print(center_text("\"Well, one of my non-beasts will destroy you.\""))
    print()
    sleep_print()
    print(center_text("The malevolent voice ceases."))
    print()
    sleep_print()
    print(center_text(f"{hero.name} nods to the residents and departs for the infected land."))
    print()
    sleep_print()
    print(center_text("The hero readies their sword and shield ready to fight!"))
    print()
    sleep_print()
    print(center_text(f"All types of evil non-beasts plod toward the hero."))
    print()
    sleep_print()
    print(center_text("Towering skeletons beat the earth with a bone."))
    print()
    sleep_print()
    print(center_text("Decaying ghouls moan as pus oozes from their bodies."))
    print()
    sleep_print()
    print(center_text("A mummy walks around with their arms extended."))
    print()
    sleep_print()
    print(center_text("A lich practices their evil magic."))
    print()
    sleep_print()
    print(center_text("Banshees howl as they soar around."))
    non_beast_battle()


def after_human_battle_story() -> None:
    """Displays the game's storyline after the hero defeats the human.
    :return: None
    """
    from hero import hero  # Placing the import statement here to avoid a circular import error
    print()
    sleep_print()
    print(center_text("After the battle the other humans fade away."))
    print()
    sleep_print()
    print(center_text("However, the land doesn't heal as before."))
    print()
    sleep_print()
    print(center_text(f"{hero.name} appears puzzled."))
    regain_health()
    improve_loadout()
    print()
    sleep_print()
    print(center_text("A tall column of flames appears in the middle of the land."))
    print()
    sleep_print()
    print(center_text("The hero retakes their battle stance, ready to fight again."))
    print()
    sleep_print()
    print(center_text("The flames disappear and a man wearing deep red tunic appears."))
    print()
    sleep_print()
    print(center_text(f"\"Hello, {hero.name}. Oh yes, I know your name.\""))
    print()
    sleep_print()
    print(center_text(f"\"I also know who you are, and what you are.\""))
    print()
    sleep_print()
    print(center_text(f"\"You are...special. I think you already know that.\""))
    print()
    sleep_print()
    print(center_text(f"\"That's why you were able to defeat all my creations.\""))
    print()
    sleep_print()
    print(center_text(f"\"But you aren't as special as me.\""))
    print()
    sleep_print()
    print(center_text(f"\"I will show the person who sent you here that now!\""))
    villain_battle()


def after_non_beast_battle_story() -> None:
    """Displays the game's storyline after the hero defeats the non-beast.
    :return: None
    """
    from hero import hero  # Placing the import statement here to avoid a circular import error
    print()
    sleep_print()
    print(center_text("After the battle the other non-beasts melt into puddles."))
    print()
    sleep_print()
    print(center_text("The puddles bubble as if they were boiling."))
    print()
    sleep_print()
    print(center_text("A little later the puddles evaporate."))
    print()
    sleep_print()
    print(center_text("Eventually the land is free of the non-beasts."))
    print()
    sleep_print()
    print(center_text("The hero walks around looking around at the changes."))
    print()
    sleep_print()
    print(center_text("A portion of the land separates and a river forms."))
    print()
    sleep_print()
    print(center_text("Plateaus and hills rise from the ground around the river."))
    print()
    sleep_print()
    print(center_text("Bushes sprout from the ground with little tufts of green grass."))
    regain_health()
    improve_loadout()
    print()
    print(center_text("A sinister groan travels through the land."))
    print()
    sleep_print()
    print(center_text("The hero and the residents look around in confusion."))
    print()
    sleep_print()
    print(center_text("The malevolent voice returns:"))
    print()
    sleep_print()
    print(center_text("\"You defeated my non-beast with a quickness.\""))
    print()
    sleep_print()
    print(center_text("\"How? Where did you get your power?\""))
    print()
    sleep_print()
    print(center_text("\"I thought you were one of those pitiful humans, but you aren't.\""))
    print()
    sleep_print()
    print(center_text("\"Why don't you respond to my questions?\""))
    print()
    sleep_print()
    print(center_text("\"Do you not understand what I am? Who I am?\""))
    print()
    sleep_print()
    print(center_text("\"Fine. Stay silent. One of MY humans will make you talk!\""))
    print()
    sleep_print()
    print(center_text("The malevolent voice ceases."))
    print()
    sleep_print()
    print(center_text(f"{hero.name} nods to the residents and departs for the infected land."))
    print()
    sleep_print()
    print(center_text("The hero readies their sword and shield ready to fight!"))
    print()
    sleep_print()
    print(center_text(f"All types of evil humans stand on the land staring at the hero."))
    print()
    sleep_print()
    print(center_text("A lumberjack with a crazed look holds a bloody axe."))
    print()
    sleep_print()
    print(center_text("A mage holds a rotating ball of fire in one of his hands."))
    print()
    sleep_print()
    print(center_text("A rouge twirls his knives in his hands over and over."))
    print()
    sleep_print()
    print(center_text("A spearman points their spear at the hero."))
    print()
    sleep_print()
    print(center_text("Finally, a cultist kneels on the ground praying in an unknown language."))
    human_battle()
