#!/usr/bin/python3
"""This module provides the storyline after each battle."""
from battles import human_battle, non_beast_battle, villain_battle
from console import console
from improve_loadout import improve_loadout
from regain_health import regain_health
from text_display_tools import sleep_print


def after_beast_battle_story() -> None:
    """Displays the game's storyline after the hero defeats the beast.
    :return: None
    """
    from hero import hero  # Placing the import statement here to avoid a circular import error
    console.print()
    sleep_print()
    console.print("After the battle the other beasts start to disintegrate.", justify="center")
    console.print()
    sleep_print()
    console.print("The wind picks up and blows away the remnants.", justify="center")
    console.print()
    sleep_print()
    console.print("Eventually the land is free of the beasts.", justify="center")
    console.print()
    sleep_print()
    console.print("The hero walks around looking around at the changes.", justify="center")
    console.print()
    sleep_print()
    console.print("Green grass appears and spreads out.", justify="center")
    console.print()
    sleep_print()
    console.print("All types of flowers bloom within the lush blades.", justify="center")
    console.print()
    sleep_print()
    console.print("Trees shoot up from the ground and extend their branches.", justify="center")
    regain_health()
    improve_loadout()
    console.print()
    console.print("An evil scream reverberates through the land.", justify="center")
    console.print()
    sleep_print()
    console.print("The hero and the residents look around in confusion.", justify="center")
    console.print()
    sleep_print()
    console.print("Then the malevolent voice returns:", justify="center")
    console.print()
    sleep_print()
    console.print("\"You defeated my beast?\"", justify="center")
    console.print()
    sleep_print()
    console.print("\"I underestimated you.\"", justify="center")
    console.print()
    sleep_print()
    console.print("\"Well, one of my non-beasts will destroy you.\"", justify="center")
    console.print()
    sleep_print()
    console.print("The malevolent voice ceases.", justify="center")
    console.print()
    sleep_print()
    console.print(f"{hero.name} nods to the residents and departs for the infected land.", justify="center")
    console.print()
    sleep_print()
    console.print("The hero readies their sword and shield ready to fight!", justify="center")
    console.print()
    sleep_print()
    console.print(f"All types of evil non-beasts plod toward the hero.", justify="center")
    console.print()
    sleep_print()
    console.print("Towering skeletons beat the earth with a bone.", justify="center")
    console.print()
    sleep_print()
    console.print("Decaying ghouls moan as pus oozes from their bodies.", justify="center")
    console.print()
    sleep_print()
    console.print("A mummy walks around with their arms extended.", justify="center")
    console.print()
    sleep_print()
    console.print("A lich practices their evil magic.", justify="center")
    console.print()
    sleep_print()
    console.print("Banshees howl as they soar around.", justify="center")
    non_beast_battle()


def after_human_battle_story() -> None:
    """Displays the game's storyline after the hero defeats the human.
    :return: None
    """
    from hero import hero  # Placing the import statement here to avoid a circular import error
    console.print()
    sleep_print()
    console.print("After the battle the other humans fade away.", justify="center")
    console.print()
    sleep_print()
    console.print("However, the land doesn't heal as before.", justify="center")
    console.print()
    sleep_print()
    console.print(f"{hero.name} appears puzzled.", justify="center")
    regain_health()
    improve_loadout()
    console.print()
    sleep_print()
    console.print("A tall column of flames appears in the middle of the land.", justify="center")
    console.print()
    sleep_print()
    console.print("The hero retakes their battle stance, ready to fight again.", justify="center")
    console.print()
    sleep_print()
    console.print("The flames disappear and a man wearing deep red tunic appears.", justify="center")
    console.print()
    sleep_print()
    console.print(f"\"Hello, {hero.name}. Oh yes, I know your name.\"", justify="center")
    console.print()
    sleep_print()
    console.print(f"\"I also know who you are, and what you are.\"", justify="center")
    console.print()
    sleep_print()
    console.print(f"\"You are...special. I think you already know that.\"", justify="center")
    console.print()
    sleep_print()
    console.print(f"\"That's why you were able to defeat all my creations.\"", justify="center")
    console.print()
    sleep_print()
    console.print(f"\"But you aren't as special as me.\"", justify="center")
    console.print()
    sleep_print()
    console.print(f"\"I will show the person who sent you here that now!\"", justify="center")
    villain_battle()


def after_non_beast_battle_story() -> None:
    """Displays the game's storyline after the hero defeats the non-beast.
    :return: None
    """
    from hero import hero  # Placing the import statement here to avoid a circular import error
    console.print()
    sleep_print()
    console.print("After the battle the other non-beasts melt into puddles.", justify="center")
    console.print()
    sleep_print()
    console.print("The puddles bubble as if they were boiling.", justify="center")
    console.print()
    sleep_print()
    console.print("A little later the puddles evaporate.", justify="center")
    console.print()
    sleep_print()
    console.print("Eventually the land is free of the non-beasts.", justify="center")
    console.print()
    sleep_print()
    console.print("The hero walks around looking around at the changes.", justify="center")
    console.print()
    sleep_print()
    console.print("A portion of the land separates and a river forms.", justify="center")
    console.print()
    sleep_print()
    console.print("Plateaus and hills rise from the ground around the river.", justify="center")
    console.print()
    sleep_print()
    console.print("Bushes sprout from the ground with little tufts of green grass.", justify="center")
    regain_health()
    improve_loadout()
    console.print()
    console.print("A sinister groan travels through the land.", justify="center")
    console.print()
    sleep_print()
    console.print("The hero and the residents look around in confusion.", justify="center")
    console.print()
    sleep_print()
    console.print("The malevolent voice returns:", justify="center")
    console.print()
    sleep_print()
    console.print("\"You defeated my non-beast with a quickness.\"", justify="center")
    console.print()
    sleep_print()
    console.print("\"How? Where did you get your power?\"", justify="center")
    console.print()
    sleep_print()
    console.print("\"I thought you were one of those pitiful humans, but you aren't.\"", justify="center")
    console.print()
    sleep_print()
    console.print("\"Why don't you respond to my questions?\"", justify="center")
    console.print()
    sleep_print()
    console.print("\"Do you not understand what I am? Who I am?\"", justify="center")
    console.print()
    sleep_print()
    console.print("\"Fine. Stay silent. One of MY humans will make you talk!\"", justify="center")
    console.print()
    sleep_print()
    console.print("The malevolent voice ceases.", justify="center")
    console.print()
    sleep_print()
    console.print(f"{hero.name} nods to the residents and departs for the infected land.", justify="center")
    console.print()
    sleep_print()
    console.print("The hero readies their sword and shield ready to fight!", justify="center")
    console.print()
    sleep_print()
    console.print(f"All types of evil humans stand on the land staring at the hero.", justify="center")
    console.print()
    sleep_print()
    console.print("A lumberjack with a crazed look holds a bloody axe.", justify="center")
    console.print()
    sleep_print()
    console.print("A mage holds a rotating ball of fire in one of his hands.", justify="center")
    console.print()
    sleep_print()
    console.print("A rouge twirls his knives in his hands over and over.", justify="center")
    console.print()
    sleep_print()
    console.print("A spearman points their spear at the hero.", justify="center")
    console.print()
    sleep_print()
    console.print("Finally, a cultist kneels on the ground praying in an unknown language.", justify="center")
    human_battle()
