#!/usr/bin/python3
"""This module contains the constants for the game."""

# Hero
HEALTH = 100
WEAPON_TYPE = "Sword"
BASE_SWORD_DAMAGE = 10
ARMOR_TYPE = "Regular Armor"
ARMOR_DEFENSE = 5

# Beast Villains
BEAST_CLASS_TYPE = "Non-human"
BEAST_RACE_TYPE = "N/A"
BEAST_WEAPON_DAMAGE = 10
BEAST_ARMOR_TYPE = "None"
BEAST_ARMOR_DEFENSE = 0
BEAST_HEALTH = 20

# Human Villains
HUMAN_CLASS_TYPE = "Human"
HUMAN_WEAPON_DAMAGE = 20
HUMAN_ARMOR_TYPE = "Sturdy Armor"
HUMAN_ARMOR_DEFENSE = 5
HUMAN_HEALTH = 40

# Non-beast Villains
NON_BEAST_CLASS_TYPE = "Non-human"
NON_BEAST_RACE_TYPE = "Undead"
NON_BEAST_WEAPON_DAMAGE = 15
NON_BEAST_ARMOR_TYPE = "None"
NON_BEAST_ARMOR_DEFENSE = 0
NON_BEAST_HEALTH = 30

# Main Villain
MAIN_VILLAIN_CLASS_TYPE = "?"
MAIN_VILLAIN_RACE_TYPE = "?"
MAIN_VILLAIN_WEAPON_DAMAGE = 25
MAIN_VILLAIN_ARMOR_TYPE = "Improved Armor"
MAIN_VILLAIN_ARMOR_DEFENSE = 8
MAIN_VILLAIN_HEALTH = 60