#!/usr/bin/python3
from battles import *
from hero import hero
from text_display_tools import *


def get_the_hero_name() -> str:
    """ Gets the hero's name from the player.    
    :return: A string of the hero's name.
    """
    print(center_text("What is your name, hero?"))
    print()
    try:
        hero.name = input("Enter your name here: ").capitalize()
        if len(hero.name) >= 20:
            print()
            print(center_text("I cannot remember that long of a name. Please enter a shorter one."))
            sleep_print()
            get_the_hero_name()
        elif hero.name == "":
            print()
            print(center_text("Are you sure you don't have a name? Everyone has a name."))
            sleep_print()
            print()
            hero.name = input("Enter your name here: ").capitalize()
            if hero.name == "":
                print()
                print(center_text("Well, I'll just call you Hero."))
                sleep_print()
                hero.name = "Hero"  # Default name for the hero if the player doesn't provide one
        return hero.name
    except ValueError:
        print()
        print(center_text("-" * 80))
        print(center_text("!! The name can only contain letters !!"))
        print(center_text("-" * 80))
        print()
        sleep_print()
        get_the_hero_name()
        print()


def story_intro() -> None:
    """
    This function displays the game's storyline.
    :return: None
    """
    clear_screen()
    print()
    print(center_text("-" * 80))
    print(center_text("The storyline of THE INFECTED LAND"))
    print(center_text("-" * 80))
    print()
    sleep_print()
    print(center_text("Infection ruins the land."))
    print()
    sleep_print()
    print(center_text("Residents huddle in their homes."))
    print()
    sleep_print()
    print(center_text("Evil beasts, non-beasts, and humans roam the land."))
    print()
    sleep_print()
    print(center_text("The residents pray for help."))
    print()
    sleep_print()
    print(center_text("It arrives in a flash of lightning and a clap of thunder."))
    print()
    sleep_print()
    print(center_text("A hero stands at the entrance to the infected land."))
    print()
    sleep_print()
    get_the_hero_name()
    print()
    print(center_text(f"{hero.name} holds a sword and a shield."))
    print()
    sleep_print()
    print(center_text("The sun reflects off the hero's metal armor."))
    print()
    sleep_print()
    print(center_text("Suddenly, a malevolent voice fills the air:"))
    print()
    sleep_print()
    print(center_text("\"You come to save the people and the land.\""))
    print()
    sleep_print()
    print(center_text("\"Go ahead and try. You will fail.\""))
    print()
    sleep_print()
    print(center_text("\"I called one of my beasts to destroy you.\""))
    print()
    sleep_print()
    print(center_text("\"Then I called one of my non-beasts.\""))
    print()
    sleep_print()
    print(center_text("\"Oh, and I called one of my humans.\""))
    print()
    sleep_print()
    print(center_text("\"I await your defeat.\""))
    print()
    sleep_print()
    print(center_text("\"It's been too long since I had a good laugh.\""))
    print()
    sleep_print()
    print(center_text("The malevolent voice ceases."))
    print()
    sleep_print()
    print(center_text(f"{hero.name} walks into the infected land ready to fight!"))
    print()
    sleep_print()
    print(center_text(f"All types of evil beasts surround the hero."))
    print()
    sleep_print()
    print(center_text("Bats glide through the sky."))
    print()
    sleep_print()
    print(center_text("Wolves travel in packs."))
    print()
    sleep_print()
    print(center_text("A massive black bear lumbers around."))
    print()
    sleep_print()
    print(center_text("Wild boars root around."))
    print()
    sleep_print()
    print(center_text("Feral dogs sniff the air and growl."))
    print()
    sleep_print()
    clear_screen()
    beast_battle()
