#!/usr/bin/python3
from beast_battle import beast_battle
from clear_screen import clear_screen
from hero import hero
from sleep_print import sleep_print


def get_the_hero_name():
    print("What is your name, hero?")
    try:
        hero.name = input("Enter your name here: ").capitalize()
        if len(hero.name) >= 20:
            print()
            print("I cannot remember that long of a name. Please enter a shorter one.")
            sleep_print()
            get_the_hero_name()
        elif hero.name == "":
            print()
            print("Are you sure you don't have a name? Everyone has a name.")
            sleep_print()
            print()
            hero.name = input("Enter your name here: ").capitalize()
            if hero.name == "":
                print()
                print("Well, I'll just call you Hero.")
                sleep_print()
                hero.name = "Hero"  # Default name for the hero is the player doesn't provide one
    except ValueError:
        print()
        print("*" * 60)
        print("!! The name can only contain letters !!".center(55))
        print("*" * 60)
        print()
        sleep_print()
        get_the_hero_name()
        print()


def story_intro() -> None:
    """
    This function displays the game's storyline.
    :return: None
    """
    clear_screen()
    print()
    print("*" * 60)
    print("The storyline of THE INFECTED LAND".center(55))
    print("*" * 60)
    print()
    sleep_print()
    print("Infection ruins the land.".center(55))
    print()
    sleep_print()
    print("Residents huddle in their homes.".center(55))
    print()
    sleep_print()
    print("Evil beasts, non-beasts, and humans roam the land.".center(55))
    print()
    sleep_print()
    print("The residents pray for help.".center(55))
    print()
    sleep_print()
    print("It arrives in a flash of lightning and a clap of thunder.".center(55))
    print()
    sleep_print()
    print("A hero stands at the entrance to the infected land.".center(55))
    print()
    sleep_print()
    get_the_hero_name()
    print()
    print(f"{hero.name} holds a sword and a shield.".center(55))
    print()
    sleep_print()
    print("The sun reflects off the hero's metal armor.".center(55))
    print()
    sleep_print()
    print("Suddenly, a malevolent voice fills the air:".center(55))
    print()
    sleep_print()
    print("\"You come to save the people and the land.\"".center(55))
    print()
    sleep_print()
    print("\"Go ahead and try. You will fail.\"".center(55))
    print()
    sleep_print()
    print("\"I called one of my beasts to destroy you.\"".center(55))
    print()
    sleep_print()
    print("\"Then I called one of my non-beasts.\"".center(55))
    print()
    sleep_print()
    print("\"Oh, and I called one of my humans.\"".center(55))
    print()
    sleep_print()
    print("\"I await your defeat.\"".center(55))
    print()
    sleep_print()
    print("\"It's been too long since I had a good laugh.\"".center(55))
    print()
    sleep_print()
    print("The malevolent voice ceases.".center(55))
    print()
    sleep_print()
    print(f"{hero.name} walks into the infected land ready to fight!".center(55))
    print()
    sleep_print()
    print(f"All types of evil beasts surround the hero.".center(55))
    print()
    sleep_print()
    print("Bats glide through the sky.".center(55))
    print()
    sleep_print()
    print("Wolves travel in packs.".center(55))
    print()
    sleep_print()
    print("A massive black bear lumbers around.".center(55))
    print()
    sleep_print()
    print("Wild boars root around.".center(55))
    print()
    sleep_print()
    print("Feral dogs sniff the air and growl.".center(55))
    print()
    sleep_print()
    clear_screen()
    beast_battle()
