#!/usr/bin/python3
from text_display_tools import *
from villain import *
import sys


def the_ending_choice() -> None:
    """Starts the hero's final decision during the ending
    :return: None
    """
    print()
    from hero import hero  # Placing the import statement here to avoid a circular import error
    print(center_text("-" * 80))
    print(center_text(f"{hero.name}, choose your action: (S) Stay or (L) Leave."))
    print(center_text("-" * 80))
    user_input = input("Enter your choice here: ").capitalize()
    try:
        if user_input == "S":
            print()
            sleep_print()
            print(center_text("\"I will stay here to protect all of you.\""))
            print()
            sleep_print()
            print(center_text("\"What if you turn evil?\""))
            print()
            sleep_print()
            print(center_text("\"I won't. I'm strong enough to fight it from overtaking me.\""))
            print()
            sleep_print()
            print(center_text("\"We shall see.\""))
            sleep_print()
            print(center_text("-- THE END --"))
            print()
            sys.exit()
        elif user_input == "L":
            print()
            sleep_print()
            print(center_text("\"I will leave. I don't want to turn evil.\""))
            print()
            sleep_print()
            print(center_text("\"Do you think that will happen?\""))
            print()
            sleep_print()
            print(center_text("\"It could. I rather not take that risk.\""))
            print()
            sleep_print()
            print(center_text("The residents nod."))
            print()
            sleep_print()
            print(center_text(f"{hero.name} disappears in a flash of lightning and a clap of thunder."))
            sleep_print()
            print(center_text("-- THE END --"))
            print()
            sys.exit()
        else:
            print()
            print(center_text("-" * 80))
            print(center_text("!! Incorrect input !!"))
            print(center_text("-" * 80))
            sleep_print()
            clear_screen()
            the_ending_choice()
    except ValueError:
        print()
        print(center_text("-" * 80))
        print(center_text("!! Please enter either S or L !!"))
        print(center_text("-" * 80))
        print()
        sleep_print()
        clear_screen()
        the_ending_choice()


def the_ending() -> None:
    """Displays the ending of the game.
    :return: None
    """
    from hero import hero  # Placing the import statement here to avoid a circular import error
    print()
    sleep_print()
    print(center_text(f"{main_villain.name} collapses onto the ground and blood gushes out of his body."))
    print()
    sleep_print()
    print(center_text(f"{hero.name} stands over the {main_villain.name}."))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"Go ahead and kill me.\""))
    print()
    sleep_print()
    print(center_text(f"{hero.name}: \"Who are you?\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"I forgot my name. It's been so long since anyone used it.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"I was sent by The Great Power long ago.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"I was good. I was pure.\""))
    print()
    sleep_print()
    print(center_text(f"{hero.name}: \"What happened? Why did you become evil?\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"Corruption.\""))
    print()
    sleep_print()
    print(center_text(f"{hero.name}: \"I don't understand.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"I don't either. I started having bad thoughts.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"I thought about killing the people.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"I thought about destroying the land.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"Eventually, I succumbed to my thoughts.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"It will happen to you if you stay here.\""))
    print()
    sleep_print()
    print(center_text(f"{hero.name}: \"I won't. I'm strong.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"So was I. Leave here. Go back to The Great Power.\""))
    print()
    sleep_print()
    print(center_text(f"{hero.name}: \"These residents need me!\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"They will survive without you. They did without me.\""))
    print()
    sleep_print()
    print(center_text(f"{hero.name}: \"I'm not like you.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name}: \"You will become like me. Learn from my mistake.\""))
    print()
    sleep_print()
    print(center_text(f"{hero.name}: \"You're trying to manipulate me. It won't work.\""))
    print()
    sleep_print()
    print(center_text(f"{main_villain.name} sighs and closes his eyes."))
    print()
    sleep_print()
    print(center_text("His body erupts into flames. The fire burns fast."))
    print()
    sleep_print()
    print(center_text("Smoke rises from the scattered ashes."))
    print()
    sleep_print()
    print(center_text(f"The residents walk over to {hero.name}. One of them steps forward."))
    print()
    sleep_print()
    print(center_text("\"So will you stay with us, or will you leave?\""))
    the_ending_choice()
